app:
  name: auth-service
  log_level: debug
  trace:
    endpoint: "localhost:4318"

http:
  host: "0.0.0.0"
  port: 8081

grpc:
  host: "0.0.0.0"
  port: 9091

cors:
  allowed_origins:
    - "http://localhost:3000"

database:
  mongodb:
    uri: "mongodb://indal:indal@localhost:27017"
    database: "products"
    timeout: "10s"
    max_pool_size: 50
