app:
  name: user-service
  env: dev
  log_level: debug
  trace:
    endpoint: "localhost:4318"

http:
  host: "0.0.0.0"
  port: 8081

grpc:
  host: "0.0.0.0"
  port: 9091

cors:
  allowed_origins:
    - "http://localhost:3000"

database:
  postgres:
    name: "users"
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "postgres"
    ssl_mode: false
    max_open_conns: 25
    max_idle_conns: 25
    conn_max_lifetime: "30m"
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "users"
    username: "mongo_admin"
    password: "mongo_pass"
    auth_source: "admin"
    timeout: "10s"
    max_pool_size: 50

clients:
  product_service:
    target: "localhost"
    port: 50053
    tls:
      enabled: false
    timeouts:
      dial: 5s
      rpc: 2s
    retry:
      max_attempts: 3
      backoff_initial: 200ms
      backoff_max: 2s
      retryable_status_codes: [UNAVAILABLE, RESOURCE_EXHAUSTED]